"""PDF export service for school comparison shortlists.

Generates a PDF document comparing shortlisted schools with their
key metrics, ratings, and other details for parents to review offline.
"""

from __future__ import annotations

from typing import Any


def generate_comparison_pdf(schools: list[dict[str, Any]], title: str = "School Comparison") -> bytes:
    """Generate a PDF comparing multiple schools.

    Parameters
    ----------
    schools:
        List of school data dicts, each containing keys like 'name',
        'ofsted_rating', 'distance_km', 'address', 'postcode', etc.
    title:
        Title for the PDF document.

    Returns
    -------
    bytes
        The PDF file content as bytes.
    """
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # Subtitle
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Comparing {len(schools)} schools", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(8)

    for i, school in enumerate(schools):
        if i > 0:
            pdf.ln(4)
            # Separator line
            pdf.set_draw_color(200, 200, 200)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(4)

        # School name
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, school.get("name", "Unknown School"), new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 10)

        # Details table
        details = []
        if school.get("ofsted_rating"):
            details.append(("Ofsted Rating", school["ofsted_rating"]))
        if school.get("type"):
            details.append(("Type", school["type"]))
        if school.get("address"):
            details.append(("Address", school["address"]))
        if school.get("postcode"):
            details.append(("Postcode", school["postcode"]))
        if school.get("distance_km") is not None:
            details.append(("Distance", f"{school['distance_km']:.1f} km"))
        if school.get("age_range_from") is not None and school.get("age_range_to") is not None:
            details.append(("Age Range", f"{school['age_range_from']} - {school['age_range_to']}"))
        if school.get("gender_policy"):
            details.append(("Gender Policy", school["gender_policy"]))
        if school.get("faith"):
            details.append(("Faith", school["faith"]))
        if school.get("is_private"):
            details.append(("Type", "Private/Independent"))

        # Clubs
        clubs = school.get("clubs", [])
        breakfast_clubs = [c for c in clubs if c.get("club_type") == "breakfast"]
        afterschool_clubs = [c for c in clubs if c.get("club_type") == "after_school"]
        if breakfast_clubs:
            details.append(("Breakfast Club", "Yes"))
        if afterschool_clubs:
            details.append(("After-school Club", "Yes"))

        # Performance
        performance = school.get("performance", [])
        for perf in performance[:3]:  # Show top 3 metrics
            details.append((perf.get("metric_type", ""), perf.get("metric_value", "")))

        # Private school fees
        private_details = school.get("private_details", [])
        for pd in private_details:
            if pd.get("termly_fee"):
                details.append((f"Termly Fee ({pd.get('fee_age_group', 'General')})", f"\u00a3{pd['termly_fee']:,.0f}"))

        # Render details
        for label, value in details:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(50, 6, f"{label}:", new_x="RIGHT")
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 6, str(value), new_x="LMARGIN", new_y="NEXT")

        # Pros/cons if available
        pros = school.get("pros", [])
        cons = school.get("cons", [])
        if pros or cons:
            pdf.ln(2)
            if pros:
                pdf.set_font("Helvetica", "B", 9)
                pdf.cell(0, 6, "Pros:", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 9)
                for pro in pros:
                    pdf.cell(8, 5, "")
                    pdf.cell(0, 5, f"+ {pro}", new_x="LMARGIN", new_y="NEXT")
            if cons:
                pdf.set_font("Helvetica", "B", 9)
                pdf.cell(0, 6, "Cons:", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 9)
                for con in cons:
                    pdf.cell(8, 5, "")
                    pdf.cell(0, 5, f"- {con}", new_x="LMARGIN", new_y="NEXT")

    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    footer_text = "Generated by School Finder - https://school-finder.example.com"
    pdf.cell(0, 6, footer_text, new_x="LMARGIN", new_y="NEXT", align="C")

    return pdf.output()
